# Site settings
title: "PromptLab"
email: your-email@example.com
description: >-
  An experimental lab for prompt engineering techniques, templates, and best practices. 
  Test, refine, and discover powerful prompts for AI tools. Contributions welcome!
baseurl: "/promptlab" # the subpath of your site for GitHub Pages
url: "https://qahivelab.github.io" # the base hostname & protocol for your site

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  prompts:
    output: true
    permalink: /:collection/:name/
  tools:
    output: true
    permalink: /:collection/:name/
  guides:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "prompts"
    values:
      layout: "prompt"
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tool"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings to suppress deprecation warnings
sass:
  style: compressed
  quiet_deps: true

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 